# Generated by Django 5.2.5 on 2025-08-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
